# Generated by Django 3.0.7 on 2021-05-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField()),
                ('country', models.CharField(choices=[('nigeria', 'nigeria'), ('ghana', 'ghana')], max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Bronze',
        ),
    ]
