# Generated by Django 3.0.7 on 2021-05-13 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210513_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='country',
        ),
    ]
