# Generated by Django 3.0.7 on 2021-05-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210520_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='referral_username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
